### ISSUE TITLE
default background

### ISSUE THREAD

**Issue by psifertex** [yjwen/org-reveal#194]
Is it possible to set a default background image for all slides without having to add a:
```:PROPERTIES:
:reveal_background: ./images/filename.jpg
:reveal_background_trans: none
:END:      
``` 
to all slides?

**Comment by yjwen** [comment]
Yes, it is possible. Please use CSS to set global background for all images.

First, specify a local CSS file in your org file
```org
#+REVEAL_EXTRA_CSS: ./local.css

* Slide 1
* Slide 2
```

Then, add the following lines into the local.css file:
```css
body {
    background-image: url("hlevel.png")
}
```

Background repeating and position can be set similarly. Please refer to http://www.w3schools.com/css/css_background.asp for detail examples.

**Comment by kaushalmodi** [comment]
It would be nice to have these as keywords just as we have `#+REVEAL_TITLE_SLIDE_BACKGROUND`, `#+REVEAL_TITLE_SLIDE_BACKGROUND_SIZE`, etc.

The css method works for setting the background image only, I think that the `background-size` CSS property will work for setting size to `"100% auto"`. But how to set other reveal-specific properties like slide transition?

**Comment by kaushalmodi** [comment]
I actually tried this and it does not work:

```css
body {
    background-image: url("http://www.foo.com/bar/baz.png")
    background-size: 100% auto
}
```
