### ISSUE TITLE
Option to omit TODO keywords

### ISSUE THREAD

**Issue by novoid** [yjwen/org-reveal#432]
Hi,

I do think it would be very helpful for preparing and managing slide decks when I might get an option to ignore TODO keywords in the resulting HTML pages.

This way, any chapter/section/page might have its life-cycle which starts at NEXT (in my case), continues with STARTED and/or WAITING and usually ends with DONE. However, it should not be an issue to ignore all defined Org todo keywords (in contrast to any upper-case word of a given set).

Currently, org-reveal is producing slides where "DONE Introduction" is an example slide title.

**Comment by yjwen** [comment]
Not sure this is the expected solution. But you can hide the `DONE` by CSS. Check this org and css.
```
#+REVEAL_EXTRA_CSS: ./tmp.css
* DONE This is done
```
tmp.css:
```
.done {visibility: hidden;}
```

**Comment by novoid** [comment]
Thanks for the hint with the CSS class.

What works on my side for active and finished todo keywords is the following CSS snippet:

```
.reveal .todo {visibility: hidden;}
.reveal .done {visibility: hidden;}
```

**Comment by Dietr1ch** [comment]
Similar to the original suggestion, but it might be useful.

I ended up using this to show the TODOs and ignore the DONEs,

  * `style.css`:
    ```css
    /* Support TODOs nicely */
    .reveal .todo {
        color: indianred;
    }
    .reveal .done {
        color: yellowgreen;
        visibility: hidden;
        display: none;
    }
    ```
  * `slides.org`:
    ```org
    #+REVEAL_EXTRA_CSS: ./style.css
    ```
